### ISSUE TITLE
Create a good, readable and structured Read-me file

### ISSUE THREAD

**Issue by Kaediin** [Kaediin/IPASS#14]
### Notes
Create a readme file which, as stated on [Canvas](https://canvas.hu.nl/courses/20306) explains any particularities. These may be: Code from others, import libraries, and so on.. 

### Tasks
- [x]  Create a readme file
Write the following chapters:

- [x] About the project (School, Eelloo)
- [x] About my role (my solution)
- [x] What there is to find in the repository (and where!)
- [x] Information and explanation as to why certain libraries where imported
- [x] How to run for yourself

- [x] Have the readme checked by someone with limited technical knowledge (they must be able to understand it!)

### Definition of Done
The readme file is clearly written with no grammar-mistakes. Also is this file readable and can be understood by someone with some-to-no technical knowledge

### Time
2 hours
